[build]
  Command = "yarn build"
  Functions = "lambda"
  Publish = "build"
[template.environment]
  PS_SERVER = "PowerSchool server (https://ps.example.com)"
  STUDENT_EMAIL_DOMAIN = "Google Education domain (example.net)"
